In [1]:
import numpy as np
np.__version__

'1.20.0'

In [16]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a=np.linspace(1, 20, num=20, endpoint=True, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [29]:
#2.呈上題，將以上數列取出偶數。
b=a[a%2==0]
print(b)

[ 2  4  6  8 10 12 14 16 18 20]


In [19]:
#3.呈1題，將數列取出3的倍數。
c=a[a%3==0]
print(c)

[ 3  6  9 12 15 18]
